steps:
- name: 'python'
  args: ['pip3','install', '-r', 'requirements.txt', '--user']
  
- name: 'python'
  args: ['python3', 'operation.py', 'test1','--user']
  
-name:
  type: pending-approval
  title: Step Title
  description: Step description
  timeout:
    duration: 2
    finalState: approved
    timeUnit: minutes

- name: 'python'
  args: ['python3', 'operation.py', 'test2','--user']
  
