steps:
- name: 'python'
  args: ['pip3','install', '-r', 'requirements.txt', '--user']
  
- name: 'python'
  args: ['python3', 'operation.py', 'test1','--user']
  
- requireApproval: true

- name: 'python'
  args: ['python3', 'operation.py', 'test2','--user']
  
